<?xml version="1.0" ?>

<definitions name="Authorise.cauthority" targetNamespace="http://sal006.salnetwork.com:83/WebProviders/Authorise/CAuthority.xml" xmlns:tns="http://sal006.salnetwork.com:83/WebProviders/Authorise/CAuthority.xml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/">
    <message name="IsAuthorisedRequest">
        <part name="UserName" type="xsd:string"/>
        <part name="PassKey" type="xsd:string"/>
        <part name="AuthoriseUsername" type="xsd:string"/>
        <part name="AuthorisePassKey" type="xsd:string"/>
        <part name="WSUID" type="xsd:string"/>
    </message>
    <message name="IsAuthorisedResponse">
        <part name="Return" type="xsd:string"/>
    </message>
    <portType name="Authorise.cauthorityPortType">
        <operation name="IsAuthorised">
            <input message="tns:IsAuthorisedRequest"/>
            <output message="tns:IsAuthorisedResponse"/>
        </operation>
    </portType>
    <binding name="Authorise.cauthoritybinding" type="tns:Authorise.cauthorityPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="IsAuthorised">
        <soap:operation soapAction="http://sal006.salnetwork.com:83/WebProviders/Authorise/CAuthority.xml#IsAuthorised"/>
            <input>
                <soap:body use="encoded" namespace="http://sal006.salnetwork.com:83/WebProviders/Authorise/CAuthority.xml" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
            <soap:body use="encoded" namespace="http://sal006.salnetwork.com:83/WebProviders/Authorise/CAuthority.xml" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>
    <service name="Authorise.cauthorityService">
        <port name="Authorise.cauthorityPort" binding="tns:Authorise.cauthoritybinding">
            <soap:address location="http://sal006.salnetwork.com:82/bin/authorizeservice.cgi"/>
        </port>
    </service>
</definitions>