<definitions name="bork" targetNamespace="SoapInterop" xmlns:wsdlns="SoapInterop" xmlns:typens="SoapInterop" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:stk="http://schemas.microsoft.com/soap-toolkit/wsdl-extension" xmlns="http://schemas.xmlsoap.org/wsdl/">
 <types>
  <schema targetNamespace="SoapInterop" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" elementFormDefault="qualified">
  </schema>
 </types>

 <message name="BorkRequest">
    <part name="Chef" type="xsd:string" />
  </message>

 <message name="BorkResponse">
    <part name="Bork" type="xsd:string" />
 </message>


 <portType name="borkPortType">
  <operation name="Bork">
    <documentation>Bork - the swedish chef</documentation> 
    <input message="wsdlns:BorkRequest"/>
    <output message="wsdlns:BorkResponse"/>
  </operation>
 </portType>

 <binding name="borkBinding" type="wsdlns:borkPortType">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
   <operation name="Bork">
    <soap:operation soapAction="#Bork"/>
     <input>
      <soap:body use="encoded" namespace="SoapInterop" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
     </input>
     <output>
      <soap:body use="encoded" namespace="SoapInterop" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
     </output>
    </operation>
 </binding>

 <service name="bork">
  <documentation>Bork - the swedish chef</documentation> 
  <port name="IBaseDataTypes" binding="wsdlns:borkBinding">
   <soap:address location="http://www.x-ws.de/cgi-bin/bork/bork.wsdl"/>
  </port>
</service>
</definitions>


